### ISSUE TITLE
Aether Highlands Gravel Annoyance

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#6] opened 2020-06-03 07:08 UTC
The new Aether Highlands having a mix of gravel within their composition leads to many holes among thin islands along with the edges of thick islands. Is there anyway to atleast wait for that gravel to be block-updated manually by a player or reduce the chances of gravel overall dropping into the void due to thin surfaces?

**Comment by dfsek** [comment] 2020-06-03 23:01
The Gravel falling is caused by snow being placed on top by a Populator. I will add a check to make sure that doesn't occur on Gravel with Air underneath.

**Comment by dfsek** [comment] 2020-06-04 23:06
A fix has been implemented and will be released with 2.0.0

**Comment by DeathShadez** [comment] 2020-06-05 00:12
Thanks

**Comment by dfsek** [comment] 2020-06-07 08:10
Fixed in 2.0.0

**Closed by dfsek** 2020-06-07 08:10 UTC
Labels: bug, priority:medium
